### ISSUE TITLE
not able to start analogist with docker image

### ISSUE THREAD

**Issue by kerphi** [ezpaarse-project/analogist#53]
``` bash
kerphi@p-gully:~$ docker run -d --name anadb mongo
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
1542ba46325fbbd75e423b20306ad162ef12062b1181132722c78a8f2dcb23ae
kerphi@p-gully:~$ docker run -d --name analogist --link anadb:mongodb -p 3000:3000 ezpaarseproject/analogist
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
4279c4bf3afa7a1fa28bd4da9ba389e1c7c0c928552b0acd16ae0982916023d9
kerphi@p-gully:~$ docker log analogist
docker: 'log' is not a docker command.
See 'docker --help'.
kerphi@p-gully:~$ docker logs analogist

> analogist@0.5.0 start /opt/analogist
> node ./bin/www

/opt/analogist/app.js:36
    host: `localhost:${config.PORT}`,
          ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /opt/analogist/bin/www:40:15
    at /opt/analogist/lib/mongo.js:19:9
    at handleCallback (/opt/analogist/node_modules/mongodb/lib/utils.js:96:12)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE
npm ERR! analogist@0.5.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the analogist@0.5.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the analogist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls analogist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/analogist/npm-debug.log
```

**Comment by nojhamster** [comment]
I think pulling the last image should fix the issue, the dockerfile has been corrected some days ago to use node 4 instead of node 0.12 (cf 16f7d1aa166b7dae5b66633f4ec5e77fdad94869), which is not compatible with ES6 features like template strings and arrow functions.

**Comment by kerphi** [comment]
You were right! Sorry.
It's better with the latest images.

Maybe we should add ":latest" to the README docker commandes ? so it will check if a new version is available before running the container ?
example:

``` bash
docker run -d --name analogist --link anadb:mongodb -p 3000:3000 ezpaarseproject/analogist:latest
```

**Comment by nojhamster** [comment]
This is to be verified, but I don't think docker pulls the latest remote image automatically if it finds a local image with the good tag. (it would be inconvenient for the end user)

**Comment by kerphi** [comment]
Ok i will check later

**Comment by nojhamster** [comment]
However, the doc should probably mention a `docker pull` before the `docker run` to be sure that the latest image is used.
Edit: 1a467f25f25970a94ddd3b9469336597812e0540
